### ISSUE TITLE
True Heading request to modify the Heading conversion

### ISSUE THREAD

**Issue by bjornjm** [SignalK/signalk-to-nmea2000#104]
Hi,

I have a true heading device providing NMEA 0183 HDT messages that I feed into signal k.
Tried to configure the "Heading" conversion but failed to get the correct data showing up
on other instruments. My conclusion is that the conversion by default sets Reference: magnetic
and the already correct data is recorrected by my plotter and and ends up wrong.

Short term I fixed by creating a separate trueheading.js conversion that I manually added to my library.

I am not sure about all the detials but I now can enable and I get the correct data through :-)

Would it be possible to modify the Heading conversion so you can configure magnetic or true?
I assume that would fix the issue. Or if for some reason not possible, include the TrueHeading conversion
into the plugin.

Thanks for a great solution and plug-in!

/Björn

trueheading.js:

`module.exports = (app, plugin) => {
  return {
    pgn: 127250,
    title: 'TrueHeading (127250)',
    optionKey: 'HEADINGv3',
    keys: [
      "navigation.headingTrue"
    ],
    callback: (heading) => {
      return [{
        pgn: 127250,
        SID: 87,
        Heading: heading,
        "Variation": undefined,
        Reference: "True"
      }]
    },
    tests: [{
      input: [ 1.2, 0.7 ],
      expected: [{
        "prio": 2,
        "pgn": 127250,
        "dst": 255,
        "fields": {
          "SID": 87,
          "Heading": 1.2,
          "Variation": 0.7,
          "Reference": "Magnetic"
        }
      }]
    }]
  }
}`

**Comment by sbender9** [comment]
We should just add your new conversion file. Change the optionKey to "TRUE_HEADING".

**Comment by sbender9** [comment]
And fix the test. Can you do a PR?

**Comment by bjornjm** [comment]
Great!

I am new to this but hopefully not too old to learn. I assume PR means pull request? 
Do I clone, add my file and then use the web interface to upload? I assume I can also use git
but then I also have to figure out how to authenticate myself...
I did not try to figure out how to build the test vector but assume I need to fix the respons to reflect my changes...

/Björn

**Comment by sbender9** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by sbender9** [comment]
(You need to create a fork)

**Comment by bjornjm** [comment]
Thanks, I will give it a try! getting late here in Sweden for an old man so it will be tomorrow.
