### ISSUE TITLE
Server Log Errors

### ISSUE THREAD

**Issue by s2tenacity** [SignalK/signalk-to-nmea2000#107]
The latest 2.18.0 version causes a non ending stream of log errors in signalk. Unable to pause log window.  I reverted back to 2.17.0 and the error stops. Reinstalled 2.18.0 and error reoccurs. 

Aug 17 12:00:41 TypeError: Cannot read properties of null (reading 'length') at Object.processToN2K [as to-n2k] (/home/pi/.signalk/node_modules/signalk-to-nmea2000/index.js:174:37) at processOutput (/home/pi/.signalk/node_modules/signalk-to-nmea2000/index.js:200:39) at FullSignalK.<anonymous> (/home/pi/.signalk/node_modules/signalk-to-nmea2000/index.js:222:9) at FullSignalK.emit (node:events:526:35) at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8) at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18) at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21) at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:233:38) at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:83:17) at Simple.emit (node:events:526:35) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10) at Simple._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:122:8) at Transform._write (node:internal/streams/transform:175:8) at writeOrBuffer (node:internal/streams/writable:392:12)

**Comment by s2tenacity** [comment]
Happens regardless of PGNs active.

**Comment by sbender9** [comment]
What version of the server are you running?

**Comment by s2tenacity** [comment]
version 2.8.3

**Comment by sbender9** [comment]
I think I fixed it. Please confirm?

**Comment by s2tenacity** [comment]
Fixed!  Thanks for the quick action.

**Comment by sbender9** [comment]
thanks for letting me know!
