### ISSUE TITLE
Problems with pgn 127489 sending oil temp and engine run time after input w/node red

### ISSUE THREAD

**Issue by okbayou** [SignalK/signalk-to-nmea2000#20]
The Engine temperature shows up on both SignalK and N2K
The engine oil temperature shows up on SignalK but not N2K
Engine runtime shows up on SignalK but not N2K

[{"id":"900a3572.db7bc8","type":"tab","label":"Engine Temp & Runtime","disabled":false,"info":"Engine temperature shows up locally as oil temp and engine temp.  N2K OK!\nRuntime shows up locally but not on N2K"},{"id":"8d1f1f54.20f34","type":"debug","z":"900a3572.db7bc8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":670,"y":160,"wires":[],"inputLabels":["message.payload"]},{"id":"c49b596c.3b7ac8","type":"inject","z":"900a3572.db7bc8","name":"","topic":"","payload":"","payloadType":"date","repeat":"6","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":100,"wires":[["eb5c317.4b7a3d"]]},{"id":"eb5c317.4b7a3d","type":"function","z":"900a3572.db7bc8","name":"fake runtime","func":"msg = {};\nmsg.topic = \"propulsion.port.totalEngineHours\";\nmsg.payload = 5000 ;\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":100,"wires":[["310832fb.d6b9ce"]]},{"id":"310832fb.d6b9ce","type":"signalk-send-pathvalue","z":"900a3572.db7bc8","name":"","source":"","x":610,"y":100,"wires":[]},{"id":"2a9ad7c1.d96148","type":"function","z":"900a3572.db7bc8","name":"Coolant temp","func":"tempIn = msg.payload + 273.15;\n\nmsg = {};\nmsg.topic = \"propulsion.port.temperature\";\nmsg.payload = tempIn;\n\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":180,"wires":[["8d1f1f54.20f34","838e659a.e39908"]]},{"id":"7aa5bbfd.7fb7b4","type":"rpi-ds18b20","z":"900a3572.db7bc8","topic":"","array":false,"name":"","x":270,"y":180,"wires":[["2a9ad7c1.d96148"]],"inputLabels":["28-0000043a1cb1"]},{"id":"9fbe82da.5b137","type":"inject","z":"900a3572.db7bc8","name":"","topic":"","payload":"","payloadType":"date","repeat":"10","crontab":"","once":true,"onceDelay":0.1,"x":90,"y":180,"wires":[["7aa5bbfd.7fb7b4"]]},{"id":"838e659a.e39908","type":"signalk-send-pathvalue","z":"900a3572.db7bc8","name":"","source":"","x":650,"y":240,"wires":[]},{"id":"d4b646fa.f02278","type":"inject","z":"900a3572.db7bc8","name":"","topic":"","payload":"","payloadType":"date","repeat":"10","crontab":"","once":false,"onceDelay":0.1,"x":70,"y":300,"wires":[["5c26e27d.325c8c"]]},{"id":"5c26e27d.325c8c","type":"function","z":"900a3572.db7bc8","name":"fake Oil Temp","func":"tempIn = 300;\n\nmsg = {};\nmsg.topic = \"propulsion.port.oilTemperature\";\nmsg.payload = tempIn;\n\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":320,"wires":[["5dc0d322.6088ec"]]},{"id":"5dc0d322.6088ec","type":"signalk-send-pathvalue","z":"900a3572.db7bc8","name":"","source":"","x":640,"y":320,"wires":[]}]

**Comment by sbender9** [comment]
I just released a new signalk-to-nmea2000 with should fix this, please update and try,

**Comment by okbayou** [comment]
I used the command: sudo npm install --unsafe-perm -g signalk-server
Then I rebooted and started the server.  Same result.

**Comment by sbender9** [comment]
You need to update the plugin via the AppStore. Not the server.

**Comment by okbayou** [comment]
I updated the plugin and rebooted.  I now have oil temp.  However I lost the alternator voltage which was 12.5 is now showing 296.90 volts.  Still nothing on runtime.

**Comment by sbender9** [comment]
I just published signalk-to-nmea2000 v2.2.3, it fixes the alternator voltage issue

**Comment by okbayou** [comment]
Everything works now, thanks!
