### ISSUE TITLE
"nmea2000out" not triggered

### ISSUE THREAD

**Issue by kledom** [SignalK/signalk-to-nmea2000#31]
I'm having some problems using this plugin. Can anybody help me?

I want to send NMEA2000 messages to a Actisense NGT-1 device. I'm running the latest signalk-server-node v.1.17.0. After activating the relevant PGNs in plugin config, I see the plugin periodically emitting the "nmea2000out" event (export DEBUG signalk-to-nmea2000). However, the event callback in providers/execute is never called (I figured that out by inserting some debug output messages in providers/execute,). Is this a known bug in the latest signalk-server-node version?

My provider settings:
    {
      "id": "actisense",
      "pipeElements": [
        {
          "type": "providers/execute",
          "options": {
            "command": "actisense-serial /dev/actisense",
            "toChildProcess": "nmea2000out"
          }
        },
        {
          "type": "providers/liner"
        },
        {
          "type": "providers/canboatjs"
        },
        {
          "type": "providers/n2k-signalk"
        }
      ]
    }

**Comment by kledom** [comment]
I seems to work when I use canboatjs instead of providers/execute. Did anything in the provider api change?

**Comment by tkurki** [comment]
nmea2000out works only when canboatjs is managing the connection.
