### ISSUE TITLE
nmea2000 not being sent

### ISSUE THREAD

**Issue by danka74** [SignalK/signalk-to-nmea2000#53]
Dear All,
running SignalK v1.37.6 and signalk-to-nmea2000 v2.12.0. After an update NMEA is not longer sent (or at least is not received). I check the logs and it seems canbusjs is sending (canboatjs:canbus log enabled):

```
Mar 05 17:24:32 2021-03-05T16:24:32.335Z canboatjs:canbus 2021-03-05T16:24:32.334Z,2,127250,100,255,8,57,67,2f,ff,7f,00,00,fd
Mar 05 17:24:32 2021-03-05T16:24:32.433Z canboatjs:canbus sending {"pgn":127250,"SID":87,"Heading":1.213414,"Variation":null,"Reference":"Magnetic"}
```

but nothing is received on the other side (i.e. my plotter). Used to work flawlessly...

Further info: using PICAN-M 
http://skpang.co.uk/catalog/picanm-with-nmea-0183-and-nmea-2000-connection-3a-smps-p-1599.html
Recieving NMEA2000 data from the bus works without any issues. Checked with Wireshark for outbound traffic but there is none.

Any further thoughts on howto debug?

Thanks,
Daniel

**Comment by sbender9** [comment]
I can't think of anything that changed to cause this, but I will do some testing this week to make sure it still works for me. Will update you as soon as I can...

**Comment by Sailor-Ralf** [comment]
I have the same Problem NMEA2000 over PICAN-M to Signalk is running. Signalk send nothing to NMEA2000 wirh the Plugin signalk-to-nmea2000.

**Comment by danka74** [comment]
@Sailor-Ralf , thanks, are you using the same versions? Any ideas on how to debug? I will be checking with another plotter later in this week.

**Comment by Sailor-Ralf** [comment]
Hello,

running SignalK v1.38.1 and signalk-to-nmea2000 v2.12.0.

**Comment by danka74** [comment]
Hi All,
have borrowed a plotter from a friend and the second plotter does indeed receive updates over NMEA2000. Annoying that my plotter stopped receiving when I updated the Raspberry just to put me off track. Fishy.
Thanks,
Daniel

**Comment by danka74** [comment]
Hmm, it might be a problem here anyway. I hade the two Garmin plotters connected and the Raspberry shows up on one of the plotters (the one recieving NMEA2000 fine, 3 devices in the device list) but not on the other (the one having trouble receiving NMEA2000 from the Pi, only 2 devices in the list).
https://photos.app.goo.gl/dLm2DqJ8WyGV6JQY6
Sometimes, when switching the Raspberry on I see a device appearing for 2 second and then disappearing.

**Comment by danka74** [comment]
Looked at the canbusjs:device debug log and it might be canbusjs related, so I'll move the issue to canbusjs.
