### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by pasquale8120** [SignalK/signalk-to-nmea2000#66]
Sorry for the blanket title.
I have signalk 1.46.3.
I have can working on the rpi  (no actisense or any other dongle. I have a real SPI based can connection)
n2k input to signalk works well.
n2k output from signalk does nothing
I turned logging on in the signalk-n2k plugin and nothing appears in the log.
I see messages in the signalk stream which are enabled in the singnalk-to-n2k plugin.
I have also tried using the data fiddler.
Nothing ever appears in the log that can be attributed to the signalk-to-n2k plugin
and nothing ever goes out the can0 port (i have receivers on the can bus which are working)

It is unclear to me how the signalk-to-n2k plugin interacts with the can0 port.
For the input side the connection is clear. But the output side is mysterious.
Any help or pointers to reading materials would be appreciated.
Note that i have tried various forms of this  https://github.com/SignalK/signalk-to-nmea2000/blob/master/README.md
and all that happens is the n2k input stops and there is still no output.

**Comment by pasquale8120** [comment]
hmm.  i did not try turning on the debug logging.  good point

**Comment by sbender9** [comment]
If you are not seeing debug from the the plugin, then it I think it means the paths are not matching up. 

What data are you expecting to be sent out? Can you show hot it looks in the DataBrowser?

**Comment by pasquale8120** [comment]
these are the paths i expect to go out. and are enabled in the sk to n2k plugin.
{"context":"vessels.urn:mrn:imo:mmsi:14159","updates":[{"source":{"sentence":"APB","talker":"EC","type":"NMEA0183","label":"fromopencpn10112"},"$source":"fromopencpn10112.EC","timestamp":"2023-03-17T13:06:50.436Z","values":[{"path":"navigation.courseRhumbline.bearingOriginToDestinationTrue","value":1.3439035243424866}]}]}
{"context":"vessels.urn:mrn:imo:mmsi:14159","updates":[{"source":{"sentence":"APB","talker":"EC","type":"NMEA0183","label":"fromopencpn10112"},"$source":"fromopencpn10112.EC","timestamp":"2023-03-17T13:06:50.436Z","values":[{"path":"navigation.courseRhumbline.bearingToDestinationTrue","value":1.3439035243424866}]}]}
{"context":"vessels.urn:mrn:imo:mmsi:14159","updates":[{"source":{"sentence":"APB","talker":"EC","type":"NMEA0183","label":"fromopencpn10112"},"$source":"fromopencpn10112.EC","timestamp":"2023-03-17T13:06:50.436Z","values":[{"path":"navigation.courseRhumbline.nextPoint.ID","value":"002"}]}]}
{"context":"vessels.urn:mrn:imo:mmsi:14159","updates":[{"source":{"sentence":"APB","talker":"EC","type":"NMEA0183","label":"fromopencpn10112"},"$source":"fromopencpn10112.EC","timestamp":"2023-03-17T13:06:50.436Z","values":[{"path":"steering.autopilot.target.headingTrue","value":1.3439035243424866}]}]}

**Comment by pasquale8120** [comment]
or this view from the data viewer
<img width="938" alt="Screen Shot 2023-03-17 at 9 09 32 AM" src="https://user-images.githubusercontent.com/26225916/225914048-541c0908-8adf-40d5-88cc-ebab668560be.png">

**Comment by pasquale8120** [comment]
I previously had signalk 1.40 with the same results. upgrading did not change anything (except for annoyingly needing to subscribe to the tcp streaming port)

**Comment by sbender9** [comment]
Definitely do use socketcan-writer, that is ancient

**Comment by sbender9** [comment]
"do not"

**Comment by pasquale8120** [comment]
Yes all those paths are in the data browser and i also see them in the tcp streaming port.

**Comment by tkurki** [comment]
Try something simple first:
- make sure the plugin is enabled and debug logging is enabled
-  make sure Depth (128267) is active in  plugin config
- restart the server, you should see in the server log
```
  signalk-to-nmea2000 Depth (128267) is enabled +0ms
  signalk-to-nmea2000 keys:environment.depth.belowTransducer +1ms
  signalk-to-nmea2000 timeouts: +0ms
  signalk-to-nmea2000 environment.depth.belowTransducer undefined +0ms
```
- add this with Data Fiddler:
```
{
  "updates": [
    {
      "values": [
        {
          "path": "environment.depth.belowTransducer",
          "value": 3.14
        }
      ]
    }
  ]
}
```
and you should see 
```
  signalk-to-nmea2000 environment.depth.belowTransducer:3.14 +19s
  signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":128267,"SID":255,"Depth":3.14,"Offset":0} +1ms
```
in the server log.

This establishes that the plugin is working, is generating output and debug logging is working. Then we can debug things further.

**Comment by pasquale8120** [comment]
where is the server log.  is this the same log file that is in the home/pi/.signalk directory?

**Comment by pasquale8120** [comment]
ok. i see debug output in the server log window.  I also see it for the xte and other navigation items.  This is the output from your depth test.  Note that the attached n2k raymarine display does not show the depth.  But the canbus is working since signalk is receiving all the other n2k messages (from an AIRMAR transducer). I have tried both with the AIRMAR in the network and without.

**Comment by pasquale8120** [comment]
another simple test i did was to send time out from signalk.  The server log window showed it was going out.  but the rauymarine did not show time.
Also note that both sk and the raymarine display the data from the AIRMAR.

**Comment by pasquale8120** [comment]
Note that the raymarine allows one to search for choose the source of data.  I had it search for all sources of time data (when i had sk spit out time regularly).  and the raymarine found no sources for time data.

**Comment by sbender9** [comment]
Use canboatjs!

**Comment by pasquale8120** [comment]
just tried it.  When i use canboatjs there is still no output.  and the can input stops.  It kills the can0 link.  I need to bring it down and up again to make it work and then canboatjs kills it again

**Comment by sbender9** [comment]
Sorry, totally missed this. I don't think sending n2k works at all with "canboat", please try with "Canbus (canboatjs)" in your connection settings.

**Comment by pasquale8120** [comment]
I run this in a terminal, candump can0 | cansump2analyzer. and it just dies (output stops) once sk comes up with canboatjs. The only way to get that command line to work again is to bring down can0 and up again.
When sk is using canboat then that command line keeps working fine in the terminal.

With sk using canboatjs i get the same log messages.
But nothing that says fail or anything.  And there is NO n2k input into sk

Mar 17 11:15:55 2023-03-17T15:15:55.969Z signalk-to-nmea2000 Depth (128267) is enabled
Mar 17 11:15:55 2023-03-17T15:15:55.973Z signalk-to-nmea2000 keys:environment.depth.belowTransducer
Mar 17 11:15:55 2023-03-17T15:15:55.974Z signalk-to-nmea2000 timeouts:
Mar 17 11:15:55 2023-03-17T15:15:55.977Z signalk-to-nmea2000 environment.depth.belowTransducer undefined
Mar 17 11:15:55 2023-03-17T15:15:55.981Z signalk-to-nmea2000 System Time (126992) is enabled
Mar 17 11:15:56 signalk-server running at 0.0.0.0:3000
Mar 17 11:15:56 2023-03-17T15:15:56.986Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54956}
Mar 17 11:15:57 2023-03-17T15:15:57.987Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54957}

**Comment by pasquale8120** [comment]
Does canboatjs come with sk?  or do i have to grab a new version independantly?

**Comment by pasquale8120** [comment]
and as a side note.  How do i turn off the need for a subscription to the tcp streaming port?  my goto sanity check is to "socat - tcp:127.0.0.1:8375"   it is very clumsy to have to then send a string of characters to subscribe

**Comment by sbender9** [comment]
canboatjs comes with the server

**Comment by sbender9** [comment]
Please check the log at startup, do you see "Error: Cannot find module 'socketcan'" ?

**Comment by pasquale8120** [comment]
nope.  this is the entire log until things settle down into a routine.

Mar 17 11:15:48 Could not parse security config
Mar 17 11:15:48 ENOENT: no such file or directory, open '/home/pi/.signalk/security.json'
Mar 17 11:15:53 Could not parse security config
Mar 17 11:15:53 ENOENT: no such file or directory, open '/home/pi/.signalk/security.json'
Mar 17 11:15:55 2023-03-17T15:15:55.969Z signalk-to-nmea2000 Depth (128267) is enabled
Mar 17 11:15:55 2023-03-17T15:15:55.973Z signalk-to-nmea2000 keys:environment.depth.belowTransducer
Mar 17 11:15:55 2023-03-17T15:15:55.974Z signalk-to-nmea2000 timeouts:
Mar 17 11:15:55 2023-03-17T15:15:55.977Z signalk-to-nmea2000 environment.depth.belowTransducer undefined
Mar 17 11:15:55 2023-03-17T15:15:55.981Z signalk-to-nmea2000 System Time (126992) is enabled
Mar 17 11:15:56 signalk-server running at 0.0.0.0:3000
Mar 17 11:15:56 2023-03-17T15:15:56.986Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54956}
Mar 17 11:15:57 2023-03-17T15:15:57.987Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54957}
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/ HTTP/1.1" 200 562 "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/main.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /@signalk/vesselpositions/remoteEntry.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/436.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/784.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/316.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/270.js HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/plugins HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/loginStatus HTTP/1.1" 200 105 "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/debugKeys HTTP/1.1" 200 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/security/access/requests HTTP/1.1" 401 29 "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /signalk HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/addons HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /skServer/webapps HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 ::ffff:192.168.2.12 - - [17/Mar/2023:15:15:58 +0000] "GET /admin/img/favicon.ico HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:15:58 2023-03-17T15:15:58.987Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54958}
Mar 17 11:15:59 2023-03-17T15:15:59.987Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54959}
Mar 17 11:16:00 ::ffff:192.168.2.12 - - [17/Mar/2023:15:16:00 +0000] "GET /skServer/appstore/available HTTP/1.1" 304 - "http://192.168.2.103:3000/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
Mar 17 11:16:00 2023-03-17T15:16:00.988Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54960}
Mar 17 11:16:01 2023-03-17T15:16:01.988Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54961}
Mar 17 11:16:02 2023-03-17T15:16:02.989Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54962}
Mar 17 11:16:03 2023-03-17T15:16:03.990Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54963}
Mar 17 11:16:04 2023-03-17T15:16:04.990Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54964}
Mar 17 11:16:05 2023-03-17T15:16:05.991Z signalk-to-nmea2000 emit nmea2000JsonOut {"pgn":126992,"Date":19433,"Time":54965}

**Comment by pasquale8120** [comment]
Note that when using canboatjs, with sk_to_n2k turned off, I still get no n2k input data

**Comment by pasquale8120** [comment]
another test.  I used candump -l to save a log file.  Then i used canplayer to send that data back out again.   The data does not go out and it kills the can0 network.  I have to bring it down and up again to get it to work as a receiver.  SO any attempt to send on this link kills it. Not sure what can be wrong with it.  But non the less using canboatjs to simply read does not work.

**Comment by pasquale8120** [comment]
Ok.  progress. sort of.  I did a fresh install on a new sdcard.  did not help.
I replaced the can spi board.   and now i know why they are so cheap.  I can now send and receive with the command line tools and the data appears on the raymarine. Clearly this chinese vendor is using untested chips.
Everything works fine with command line tools from canutils and canboat.  But signalk and the can0 bus fail when i use canboatjs.  
Most interesting is when i use canboatjs and  run "top" i see that **the irq process for spi uses 66% of the cpu.**
When i use signalk with canboat (no js) the irq process does not even appear in the top 20 processes.

**Comment by pasquale8120** [comment]
to be clear.  These tools work
candump
canplayer (and the data appears on the raymarine)
socketcan-writer (and the data appears on the raymarine)
signalk+canboat (no js) also works to receive

But the signalk + canboatjs causes the irq load to skyrocket and neither receive nor send works.

**Comment by sbender9** [comment]
I just released a new canboatjs with a new utility for testing. Can you please:

`sudo npm install -g @canboat/canboatjs`

Then run

`candumpjs can0`

**Comment by pasquale8120** [comment]
the new candumpjs when run by itself works well.  It receives all the PGNs on the can network.
Not sure if signalk is supposed to use it.  but signalk still causes the irq process to spike. 
Candumpjs does not cause the irq process to spike.

**Comment by pasquale8120** [comment]
and wow.   after a reboot with the new canboatjs,    everything works.
n2k in AND n2k out works with canboatjs selected as the data connection.
And there is no spike in the irq process.   horray?

**Comment by sbender9** [comment]
Signalk would not be using the new version we installed. It has its own copy. So this would not have fixed it.

**Comment by pasquale8120** [comment]
i rebooted again and tried running signalk without first running the new canboatjs.   and it still works.

**Comment by pasquale8120** [comment]
I am very sorry about all of this.  I was able to reproduce the failure by stressing the boards.  Turns out there was a flakey ground connection between the canbus spi board and the rpi.   I seem to have wasted your time.  sorry about that.   Still doesnt explain why the canboat worked and the canboatjs did not.    This is a great piece of sw and i have been using it in my boat since 2017.   Only now adding n2k.

**Comment by pasquale8120** [comment]
by the way.   i wrote a python program for KOBO e readers and it receives signalk over wifi. I replaced all my aging display with 4 kobos.  Works extremely well. Signalk made it easy and the e-ink displays are perfect for the bright sun. I wrote this in 2017

**Comment by sbender9** [comment]
No worries! We got a new utility in canboatjs out of it. And maybe this will help someone else out in the future. 

And I agree, very strange that canboat/can-utils did not have a problem.
