### ISSUE TITLE
Simrad TP32 autopilot

### ISSUE THREAD

**Issue by MichaKersloot** [SignalK/signalk-to-nmea2000#81]
Hi,

i'm trying to get my TP32 working with routing from Avnav / SignalK. We've found some bugs and @wellenvogel already created #79 i've found that he fixed 129284, but not 129283. Also the SID is missing from 129283.

I've fixed the 19283 locally, but still no enjoy. 
Now I was watching both sentences from my B&G Vulcan and the remaining two differences in those to PGN's are in the B&G the SID is the same in both PNG's but they are increasing on every send. To implement this, it requires a bit more than copy-paste, so I hope someone can assist with this?

```
--- navigationdata.js.orig	2023-09-10 11:10:47.237208755 +0200
+++ navigationdata.js	2023-09-10 13:48:18.391593287 +0200
@@ -5,15 +5,32 @@
     title: 'Cross Track Error (129283)',
     optionKey: 'xte',
     keys: [
+      'navigation.courseGreatCircle.crossTrackError'
+    ],
+    callback: (XTE) => [{
+      pgn: 129283,
+      "SID" : 0x88,
+      XTE,
+      "XTE mode": "Autonomous",
+      "Navigation Terminated": "No"
+    }]
+  }, 
+  {
+    pgn: 129283,
+    title: 'Cross Track Error (129283)',
+    optionKey: 'xte',
+    keys: [
       'navigation.courseRhumbline.crossTrackError'
     ],
     callback: (XTE) => [{
       pgn: 129283,
+      "SID" : 0x88,
       XTE,
       "XTE mode": "Autonomous",
       "Navigation Terminated": "No"
     }]
-  }, {
+  }, 
+  {
     pgn: 129284,
     title: 'Navigation Data (129284)',
     optionKey: 'navigationdata',
```

**Comment by TwoCanPlugIn** [comment]
What happens if you set the value of the sid to 0xFF ?

**Comment by MichaKersloot** [comment]
Hi, it just took till next season, but I've been able to get a working system by reverting my changes ;-) Applying #99 and setting the software (AvNav from @wellenvogel ) to Rumbline.
