### ISSUE TITLE
Feature request : Support for PGN 130316 (Temp), 130313 ( Humidity ), and 130314 ( Atm Pressure )

### ISSUE THREAD

**Issue by torbenaa** [SignalK/signalk-to-nmea2000#87]
Dear Scott,

Can you please add support for :

- Temperature via PGN130316 ( Cabin )
- Humidity via PGN130313
- Pressure via PGN130314

BR Torben

**Comment by torbenaa** [comment]
Perhaps the temperature could be 130312 ? But you got that already as "Temperature, exhaust". Why is that ? 
I believe that PGN can hold temperatures for all kinds of sources ? https://canboat.github.io/canboat/canboat.html#lookup-TEMPERATURE_SOURCE

**Comment by IanLeeClaxton** [comment]
Raymarine only support 130316 for inside temp

**Comment by torbenaa** [comment]
I finally got the time to play with this. It seems like my Raymarine MFD / Lighthouse is receiving the PGN 130313 ( Humidity ) value - but it shows 0 or 1 percent. The unit i SK is ratio.
Could it be that the value sent with PGN130313 should be in percent ?

**Comment by IanLeeClaxton** [comment]
![Screenshot_20240729-192012](https://github.com/user-attachments/assets/57aac3bd-3665-4ff7-81f4-e6cebb2968e6)
This is the info from the lighthouse v4 docs

**Comment by IanLeeClaxton** [comment]
https://acrobat.adobe.com/id/urn:aaid:sc:EU:1194db41-9491-451a-9d1c-9baef6f1822e

**Comment by torbenaa** [comment]
Thanks Ian - but it is not clear to me if the value should be in percent (0-100) or ratio (0-1).
Looks like Raymarine is expecting percent ?

**Comment by torbenaa** [comment]
@sbender9 - do you have thoughts on this ? Could it be that the ratio value in SK should be multiplied by 100 when sending to NMEA2000 ? 
Thanks for your effort !

**Comment by IanLeeClaxton** [comment]
> Thanks Ian - but it is not clear to me if the value should be in percent (0-100) or ratio (0-1). Looks like Raymarine is expecting percent ?

My issue was with inside temp

**Comment by HcGrande** [comment]
PGN130316 would be great.  For all customers running Raymarine and Signal k with inside temps, this is PGN is currently missing in SignalK.
